# training parameters
train:
  loss: "xentropy"       # must be either xentropy or iou
  max_epochs: 1000
  max_lr: 0.01           # sgd learning rate max
  min_lr: 0.001          # warmup initial learning rate
  up_epochs: 0.3         # warmup during first XX epochs (can be float)
  down_epochs:  50       # warmdown during second XX epochs  (can be float)
  max_momentum: 0.9      # sgd momentum max when lr is mim
  min_momentum: 0.85     # sgd momentum min when lr is max
  final_decay: 0.995     # learning rate decay per epoch after initial cycle (from min lr)
  w_decay: 0.0005        # weight decay
  batch_size: 64         # batch size
  report_batch: 1        # every x batches, report loss
  report_epoch: 1        # every x epochs, report validation set
  report_batch_val: 100  # every 100 batches, report validation set
  save_summary: False    # Summary of weight histograms for tensorboard
  save_imgs: True        # False doesn't save anything, True saves some
                         # sample images (one per batch of the last calculated batch)
                         # in log folder
  avg_N: 3               # average the N best models
  crop_prop:
    height: 288
    width: 512

# backbone parameters
backbone:
  name: "mobilenetv2"
  dropout: 0.02
  bn_d: 0.05
  OS: 16 # output stride
  train: True # train backbone?
  extra:
    width_mult: 1.0
    shallow_feats: True # get features before the last layer (mn2)
    aggressive_downsample: True
    prune_last_layer: True
    use_prev_mask: False

decoder:
  name: "aspp_progressive"
  dropout: 0.02
  bn_d: 0.05
  train: True # train decoder?
  extra:
    aspp_channels: 32
    last_channels: 16
    ASPP_rates: [4, 8, 12]  # 18 x 32 map

# classification head parameters
head:
  name: "segmentation"
  dropout: 0.1

# dataset (to find parser)
dataset:
  name: "persons_augmented_v3"
  location:
   - /home/g-korepanov/datasets/coco
  workers: 10 # number of threads to get data
  img_means: # rgb
    - 0.46992042
    - 0.45250652
    - 0.42510188
  img_stds: # rgb
    - 0.29184756
    - 0.28221624
    - 0.29719201
  img_prop:
    width: 512
    height: 288
    depth: 3
  labels:
    0: 'background'
    1: 'person'
  labels_w:
    0: 1.0
    1: 1.0
  color_map: # bgr
    0: [0,0,0]
    1: [0,255,0]
    -1: [255,0,0]
  is_gen_prev_mask: False
  is_gen_prev_img: True
